### ISSUE TITLE
Simplifying build process

### ISSUE THREAD

**Issue by erasche** [bgruening/docker-recipes#14]
Just an idea... I recently found out about https://github.com/galaxyproject/galaxy-cloudman-playbook/tree/master/roles/galaxyprojectdotorg.cloudman-galaxy-setup/files/scripts and realised it had applications here, simplifying the installation process with nice yaml files.

```yaml
api_key: <Admin user API key from galaxy_instance>
galaxy_instance: <Galaxy instance IP>
tools:
- name: synapse_interface
  owner: kellrott
  tool_panel_section_id: peak_calling
  tool_shed_url: https://testtoolshed.g2.bx.psu.edu
- name: add_value
  owner: devteam
  tool_panel_section_id: textutil
  tool_shed_url: https://toolshed.g2.bx.psu.edu
```
